category: tools
title: "Firefox: ماهی ۵۰ گیگ VPN رایگان"
description: "وای خدا! تازه فهمیدم Firefox به هر کاربر ماهی ۵۰ گیگ ترافیک VPN رایگان میدهد."
date: 2026-06-30
likes: 1605
bookmarks: 2205
reposts: 360
views: 165327
url: https://x.com/realchendahuang/status/2071963210689970673
content: |
  وای خدا! تازه فهمیدم مرورگر Firefox به هر کاربر ماهی ۵۰ گیگ ترافیک VPN رایگان میدهد.

  برای آن معضل آزاردهندهی مرغ و تخممرغ خیلی به کار میآید.

  روش استفاده:

  ۱. در نوار آدرس تایپ کن `about:config`
  ۲. برو به تنظیمات پیشرفته و روی «نمایش همه» کلیک کن
  ۳. دنبال `browser.ipProtection.enabled` بگرد
  ۴. مقدار آن را به true تغییر بده