category: "ai"
title: "大家用 Gemini 都在幹什麼？"
description: "有了 Codex 之後，美國大豆包 Gemini 到底還有什麼用武之地？"
date: 2026-09-06
likes: 70
bookmarks: 50
reposts: 5
views: 109724
url: "https://x.com/realchendahuang/status/2096559458633875733"
content: |
  好奇大家用美國大豆包 Gemini 都在幹什麼？
  我感覺大多數人有了 Codex，平時根本用不上美國大豆包。
  想知道它的優點到底是什麼？
