category: "ai"
title: "Moja mapa wyboru Coding Agentów"
description: "Chińskie modele – ZCode, GPT – Codex. Liczy się szybkość? Pi. Szybkość i spokój ducha? OMP. Korporacyjne autorskie aplikacje klienckie? DSH. Chcesz budować charakter? Workbuddy."
date: 2026-09-01
likes: 115
bookmarks: 113
reposts: 6
views: 29194
url: "https://x.com/realchendahuang/status/2094587665786233213"
content: |
  To jest mój obecny układ.

  Przy chińskich modelach polecam podpiąć ZCode (DeepSeek V4 Flash, GLM 5.3 Flash i tym podobne).

  Przy GPT – od razu Codex.

  Chcesz szybkości? Użyj Pi.

  Chcesz szybkości ORAZ spokoju ducha? Użyj OMP.

  Budujesz korporacyjne aplikacje klienckie dla firm? Użyj DSH.

  Chcesz hartować swoje nerwy? Użyj Workbuddy.
