category: ai
title: "OpenCode Go 初月 5 ドルの DeepSeek V4 Flash プラン"
description: "OpenCode Go プランは初月たったの 5 ドル。"
date: 2026-08-05
likes: 161
bookmarks: 112
reposts: 14
views: 28653
url: https://x.com/realchendahuang/status/2084874129669488965
content: |
  OpenCode Go プラン、初月たったの5ドル、35元
  開通したら新しい版のDeepSeek V4 Flashモデルを使って
  実際に試したら、午前中がっつり使って、週間使用量のわずか1%しか使ってなかった。ありえん、使い切れずにまた不安になり始める wwwwww
  安い、使いやすい、速い、という不可能の三角形が、Opencode Go+DeepSeek V4 Flashの組み合わせで完璧に実現された
  Opencode https://t.co/c0k1WKWNle