category: ai
title: "OpenCode Go 首月 5 美金的 DeepSeek V4 Flash 套餐"
description: "OpenCode Go 套餐首月只需要 5 美金。"
date: 2026-08-05
likes: 157
bookmarks: 108
reposts: 14
views: 29589
url: https://x.com/realchendahuang/status/2084874129669488965
content: |
  OpenCode Go 套餐，首月只要 5 美金，約合人民幣 35 塊
  開通以後，就可以用它的新版 DeepSeek V4 Flash 模型
  實測下來，我狠狠用了一整個上午，只用了每週額度的 1%，太扯了吧，用不完又要開始焦慮了哈哈哈哈哈
  便宜、好用、速度快這個不可能三角，在 OpenCode Go + DeepSeek V4 Flash 的組合下被完美實現了
  Opencode https://t.co/c0k1WKWNle
