category: product
title: "Pas d'inspiration pour l'indie dev ? Commence par satisfaire tes propres besoins"
description: "Pour l'indie dev, si on n'a aucune inspiration sur le produit à faire."
date: 2026-06-22
likes: 7
bookmarks: 2
reposts: 0
views: 1700
url: https://x.com/realchendahuang/status/2069010510306246970
content: |
  Pour l'indie dev, si on n'a aucune inspiration sur le produit à faire.

  On peut commencer par satisfaire ses propres besoins.

  Il y a de grandes chances que des utilisateurs sur la même fréquence existent.