category: "ai"
title: "闲鱼 12 块淘来的 18 个月美国大豆包"
description: "12 块钱的美国大豆包 Gemini，启动！"
date: 2026-09-05
likes: 45
bookmarks: 10
reposts: 0
views: 15762
url: "https://x.com/realchendahuang/status/2096059568292012334"
content: |
  闲鱼12块钱买来的，18个月大的美国大豆包！
  启动！
